version: '3.8'

services:
  admin-backend:
    build: .
    container_name: admin-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:@mysql-db:3306/dashboard_db
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root  # Required for Docker socket access
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-backend.rule=Host(`app.kambaa.ai`)"
      - "traefik.http.routers.admin-backend.tls=true"
      - "traefik.http.routers.admin-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-backend.loadbalancer.server.port=8004"
    networks:
      - traefik
      - admin-network

  admin-frontend:
    image: admin-dashboard-frontend:latest
    container_name: admin-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-frontend.rule=Host(`dashboard.kambaa.ai`)"
      - "traefik.http.routers.admin-frontend.tls=true"
      - "traefik.http.routers.admin-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-frontend.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
  admin-network:
    driver: bridge

volumes:
  mysql_data: