version: '3.8'

services:
  admin-dashboard:
    build: .
    container_name: admin-dashboard
    ports:
      - "8004:8004"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-dashboard.rule=Host(`dashboard.kambaa.ai`)"
      - "traefik.http.routers.admin-dashboard.entrypoints=websecure"
      - "traefik.http.routers.admin-dashboard.tls.certresolver=myresolver"
      - "traefik.http.services.admin-dashboard.loadbalancer.server.port=8004"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://tenant_user:TenantPass123@mysql-db:3306/multi_tenant_db
    depends_on:
      - mysql-db
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: multi_tenant_db
      MYSQL_USER: tenant_user
      MYSQL_PASSWORD: TenantPass123
    ports:
      - "3306:3306"
    networks:
      - traefik-net
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

networks:
  traefik-net:
    external: true

volumes:
  mysql_data: