name: Deploy to Server

on:
  push:
    branches:
      - main   # change if you want another branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd /home/${{ secrets.USER }}/kambaa   # change to your app directory
            git pull origin main
            docker compose build --no-cache
            docker compose up -d
          EOF
